# production environment
FROM nginx:stable-alpine
WORKDIR /
COPY /build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

# Docker commands
# docker build -f Dockerfile.prod -t portfolio:prod .
# docker run -dit --restart unless-stopped -p 50001:80 portfolio:prod
